// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBePsYHUGE3yOjbvaAXFn5c9g5ExSd2MgQ',
    appId: '1:522262819217:android:f448f7a87ac6c7bee82a30',
    messagingSenderId: '522262819217',
    projectId: 'fir-series-38d1d',
    storageBucket: 'fir-series-38d1d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4iOWfxeUDXjs4YDfS21Wa9JJ5ORGfpIE',
    appId: '1:522262819217:ios:0ba828595b322b09e82a30',
    messagingSenderId: '522262819217',
    projectId: 'fir-series-38d1d',
    storageBucket: 'fir-series-38d1d.appspot.com',
    androidClientId: '522262819217-g8g1kpau4jcvnhld76msadh60tg0vgac.apps.googleusercontent.com',
    iosClientId: '522262819217-b1df6i5h9lavfep43ihb9t4n118hcedr.apps.googleusercontent.com',
    iosBundleId: 'com.example.firestoreDb',
  );
}
